config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => "homes#about"
  
  devise_for :users
  root to: "homes#top"
  
  resources :books,only:[:new,:create,:index,:show,:destroy,:edit,:update]
  resources :users,only:[:new,:create,:index,:show,:edit,:update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  validates:title,
   presence:true
   
   validates:body,
    presence:true,
    length:{maximum:200}
  
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
validates:name, length: {in: 2..20}, uniqueness:true
validates:introduction, length:{maximum:50}
         
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       redirect_to book_path(@book), notice: 'Book was successfully created.'
    else
       flash[:error] = "Book was error create"
       @books = Book.all
       @user = current_user
       render 'index'
    end
  end
  
  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
       redirect_to books_path
    end
  end
  
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end 
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end  
  end
  
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  def top
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit,:update]
  
  def ensure_correct_user
     @user = User.find(params[:id])
     unless @user.id == current_user.id
     redirect_to user_path(current_user.id)
     end
  end
  
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end
  
  def edit
    @user = User.find(params[:id])
     if @user == current_user
        render "edit"
     else
        redirect_to user_path(current_user)
     end
  end 

  def index
    @users = User.all
    #@books = Book.all
    @book = Book.new
    @user = current_user
  end
  
  def update
    @user = User.find(params[:id])
   if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
   else
    render :edit
   end
  end
  
private

def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_booksubmit.html.erb
<div class="pt-4">
 <h1>New book</h1>
 <%= form_with model: book,local:true do |f| %>
  <div class="form-group">
   <h4 class="py-2">Title</h4>
   <%= f.text_field :title,class:"form-contorol" %>
  </div>
  <div class="form-group">
   <h4 class="py-2">Option</h4>
   <%= f.text_area :body,class:"form-control" %>
  </div>

   <%= f.submit "Create Book",class:"btn btn-success" %>
 <% end %>
</div>

app/views/books/_error_message.html.erb
<% if book.errors.any? %>
  <div id="error_explanation">
   <h2><%= pluralize(book.errors.count, "error") %> prohibited this obj from being saved:</h2>
    <ul>
     <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
     <% end %>
    </ul>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container pt-3 pb5">
 <div class="row">
  <div class="col-lg-5 mx-auto">

<h1>Editing Book</h1>
   <% if @book.errors.any? %>
     <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h2>
       <ul>
        <% @book.errors.full_messages.each do |message| %>
         <li><%= message %></li>
        <% end %>
       </ul>
     </div>
   <% end %>
   <%= form_with model: @book,local:true do |f| %>
    <div class="form-group">
     <h4>Title</h4>
     <%= f.text_field :title,class:"form-control" %>
    </div>

    <div class="form-group">
     <h4>Option</h4>
     <%= f.text_area :body,class:"form-control" %>
    </div>
    <div class="py-2">
     <%= f.submit "Update Book",class:"btn btn-success" %>
    </div>
     <% if @book.user == current_user %>
      <div class="text-primary pt-2">
       <%= link_to "Show",book_path(@book),class:"btn btn-primary p-1" %>
        |
       <%= link_to "Back",books_path,class:"btn btn-secondary p-1"%>
      </div>
     <% end %>
   <% end %>
  </div>
 </div>
</div>

app/views/books/index.html.erb
<div class="container pt-3 pb-5">
  <%= render "books/error_message", book: @book %>
<div class="row">
  <div class="col-md-3 pr-1">
    <%= render "users/userinfo",user: @user %>
    <%= render "books/booksubmit",book: @book %>
  </div>

<div class="col-md-8 offset-md-1">
  <h1>Books</h1>
  <table class="table">
    <thead>
     <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      </tr>
    </thead>
    
<% @books.each do |book| %>
  <tbody>
    <tr>
     <td>
      <%= link_to user_path(book.user.id) do %>
       <%= image_tag book.user.get_profile_image(80,80) %>
      <% end %>
     </td>
     
     <td>
      <%= link_to book_path(book.id) do %>
       <%= book.title %>
      <% end %>
     </td>
     
     <td><%= book.body %></td>
     
    </tr>
  </tbody>
<% end %>
  </table>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class='container'>
 <div class='row'>
  <div class='col-md-3'>
    <h2>User info</h2>
     <%= render 'users/userinfo', user: @book.user %>
    <h2 class="mt-3">New book</h2>
     <%= render 'booksubmit', book: Book.new %>
  </div>

  <div class='col-md-8 offset-md-1'>
    <h2>Book detail</h2>
      <table class='table'>
        <tr>
          <td><%= link_to user_path(@book.user) do %>
           <%= image_tag @book.user.get_profile_image(100, 100) %>
           <%= @book.user.name %>
           <% end %>
          </td>
          
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
            <% if @book.user_id == current_user.id %>
              <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#(@book.id)" %></td>
              <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: "本当に消しますか？" }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
            <% else %>
              <td></td>
              <td></td>
            <% end %>
        </tr>
      </table>
  </div>
 </div>
</div>

app/views/books/top.html.erb
<h1>Books#top</h1>
<p>Find me in app/views/books/top.html.erb</p>

app/views/homes/about.html.erb
<dev class="container">
  <div class="row">
    <h1 class="p-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
  </div>
</dev>

app/views/homes/top.html.erb
<div class="container">
  <div class="row col-12 p-3">
    
    <div class="mx-auto">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers,</strong></p>
      <p></p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      
      <div class="col-11">
        <%= link_to "Log in",user_session_path,class:"text-light btn btn-info btn-block" %><br>
        <%= link_to "Sign up",new_user_registration_path,class:"text-light btn btn-success btn-block" %>
      </div>

    </div>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/84fa9686b5.js" crossorigin="anonymous"></script>
  </head>

  <body>
   <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
     <div class="container">
      <a class="navbar-brand" href= "/" >
       <span>Bookers</span>
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">

       <% if user_signed_in? %>
         <li><%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
         <i class="fas fa-home"></i> Home
       <% end %></li>
       
         <li><%= link_to "/users", class: 'nav-link text-light' do %>
          <i class="fas fa-users"></i> Users
             <% end %></li>
             
         <li><%= link_to books_path, class: 'nav-link text-light' do %>
          <i class="fas fa-book-open"></i> Books
             <% end %></li>
             
         <li><%= link_to destroy_user_session_path,method: :delete, class: 'nav-link text-light' do %>
          <i class="fas fa-sign-out-alt"></i> Log out
             <% end %></li>

         <% else %>
           <li><%= link_to root_path, class: 'nav-link text-light' do %>
           <i class="fas fa-home"></i> Home
               <% end %></li>
               
           <li><%= link_to home_about_path, class: 'nav-link text-light' do %>
           <i class="fas fa-link"></i> About
               <% end %></li>
               
           <li><%= link_to "/users/sign_up", class: 'nav-link text-light' do %>
           <i class="fas fa-user-plus"></i> Sign up
               <% end %></li>
               
           <li><%= link_to "/users/sign_in", class: 'nav-link text-light' do %>
           <i class="fas fa-sign-in-alt"></i> Log in
              <% end %></li>
         <% end %>
       </div>
   </header>

   <div class= "body">
     <% flash.each do |key, value| %>
       <%= content_tag(:div, value, class: "#{key}") %>
     <% end %>
   </div>
   <main>
     <%= yield %>
   </main>

   <footer>
    <div class='container mt-5'>
      <div class='row'>
       <div class='mx-auto'>
         <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/post_images/index.html.erb
<% @post_images.each do |post_image| %>
  <div>
    <%= image_tag post_image.get_image %>
    <p>投稿ユーザー画像：<%= image_tag 'sample-author1.jpg' %></p>
    <p>ショップ名：<%= post_image.shop_name %></p>
    <p>説明：<%= post_image.caption %></p>
    <p>ユーザーネーム：<%= post_image.user.name %></p>
  </div>
<% end %>

app/views/post_images/new.html.erb
<h1>画像投稿フォーム</h1>
<%= form_with model: @post_image do |f| %>
  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  <h4>ショップ名</h4>
  <%= f.text_field :shop_name %>
  <h4>説明</h4>
  <%= f.text_area :caption %>
  <%= f.submit '投稿' %>
<% end %>

app/views/post_images/show.html.erb
<div>
  <%= image_tag XXX.get_image %>
  <p>ショップ名：<%= XXX.shop_name %></p>
  <p>説明：<%= XXX.caption %></p>
  <p>投稿ユーザー画像：<%= image_tag 'sample-author1.jpg' %></p>
  <p>ユーザーネーム：<%= XXX.user.name %></p>
  <p>投稿日：<%= XXX.created_at.strftime('%Y/%m/%d') %></p>
</div>

app/views/users/_userinfo.html.erb
<h1>User info</h1>
  <table class="table">
    <tr>
      <td><%= image_tag user.get_profile_image(100,100) %></td>
      <td></td>
    </tr>
    
    <tr>
      <td>name</td>
      <td><%= user.name %></td>
    </tr>
    
    <tr>
      <td>introduction</td>
      <td><%= user.introduction %></td>
    </tr>
  </table>
  
<%= link_to edit_user_path(user.id),class:"btn btn-block btn-outline-secondary p-0 mt-3" do %>
 <i class="fas fa-user-cog"></i>
<% end %>

app/views/users/edit.html.erb
div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      
    <h2>User info</h2>
    <%= render "devise/shared/error_messages", resource: @user %>
    <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <label for="user_name">Name</label><br />
        <%= f.text_field :name, autofocus: true, id:"user_name", placeholder:"名前", class: 'form-control name'%>
      </div>
      <div class="form-group">
        <label for="inputImage">Image</label><br />
        <%= image_tag @user.profile_image, size: '60x60' if @user.profile_image.attached? %>
        <%= f.file_field :profile_image %>
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label><br />
        <%= f.text_area :introduction, rows:'5', id:"user_introduction", placeholder: "introduction", class: 'form-control introduction' %>
      </div>
      <div class="form-group">
        <%= f.submit "Update User", class: 'btn btn-secondary' %>
      </div>
    <% end %>
    
  </div>
</div>

app/views/users/index.html.erb
<div class="container pt-3 pb-5">
  <div class="row">
    <div class="col-md-3 pr-1">
      <%= render "books/error_message",book: @book %>
      <%= render "users/userinfo",user: @user %>
      <%= render "books/booksubmit",book: @book %>
    </div>
    
<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
    <table class="table table-hover table-inverse">
     <thead>
      <th>image</th>
      <th>name</th>
      <th></th>
     </thead>
     
      <tbody>
        <% @users.each do |user| %>
         <tr>
          <td><%= image_tag user.get_profile_image(100,100) %></td>
          <td><%= user.name %></td>
          <td><%= link_to"Show",user_path(user) %></td>
         </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/users/show.html.erb
<div class="container pt-3 pb-5">
  <div class="row">
    <div class="col-md-3 pr-1">
     <%= render "users/userinfo",user:@user %>
     <%= render "books/booksubmit",book:@book %>
    </div>
    
 <div class="col-md-8 offset-md-1">
  <h2>Books</h2>
   <table class="table">
    <thead>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
     <th colspan=></th>
    </thead>

<% @books.each do |book| %>
 <tbody>
  <tr>
   <td>
    <%= link_to user_path(@user.id) do %>
    <% end %>
   </td>

  <td>
   <%= link_to book_path(book.id) do %>
    <%= book.title %>
   <% end %>
   </td>
   
   <td>
    <%= book.body %>
   </td>
  </tr>
 </tbody>
 <% end %>
   </table>
   
</div>
</div>
</div> 
 
 

app/views/users/top.html.erb
<h1>Users#top</h1>
<p>Find me in app/views/users/top.html.erb</p>